// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjMuY7tdHJDtUvs_AchJ34ftFoYhODUyA',
    appId: '1:941856109059:web:4818ac14675460d54f1436',
    messagingSenderId: '941856109059',
    projectId: 'respirhythm',
    authDomain: 'respirhythm.firebaseapp.com',
    storageBucket: 'respirhythm.firebasestorage.app',
    measurementId: 'G-K2GKVQ36ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQoNF3FgIDMMIkkdPhHa4xzeB1mJh0wI',
    appId: '1:941856109059:android:e1903793f439f8ec4f1436',
    messagingSenderId: '941856109059',
    projectId: 'respirhythm',
    storageBucket: 'respirhythm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi97O_w2VfLdjSmUu55XOa_rubD1mcCPM',
    appId: '1:941856109059:ios:5ac60019dc5329584f1436',
    messagingSenderId: '941856109059',
    projectId: 'respirhythm',
    storageBucket: 'respirhythm.firebasestorage.app',
    iosBundleId: 'com.example.coen490',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi97O_w2VfLdjSmUu55XOa_rubD1mcCPM',
    appId: '1:941856109059:ios:5ac60019dc5329584f1436',
    messagingSenderId: '941856109059',
    projectId: 'respirhythm',
    storageBucket: 'respirhythm.firebasestorage.app',
    iosBundleId: 'com.example.coen490',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjMuY7tdHJDtUvs_AchJ34ftFoYhODUyA',
    appId: '1:941856109059:web:972560c8ee70c1044f1436',
    messagingSenderId: '941856109059',
    projectId: 'respirhythm',
    authDomain: 'respirhythm.firebaseapp.com',
    storageBucket: 'respirhythm.firebasestorage.app',
    measurementId: 'G-SJ79L9WWCF',
  );
}
